resolver: lts-9.21
packages:
- .
local-bin-path: bin
extra-deps:
- cyclotomic-0.4.4.1
- language-c-quote-0.12.2
- mainland-pretty-0.7
- modular-arithmetic-1.2.1.5
- libltdl-0.1.1.1
- vector-fftw-0.1.3.8
